/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AnimeDAO;
import dao.AnimeListDAO;
import dao.AnimeRatingDAO;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.Anime;
import model.AnimeList;
import model.User;

/**
 *
 * @author andre
 */
public class AnimeDetailPage extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnimeDetailPage.class.getName());
    protected Anime source_anime;
    protected MainPage main_page;
    protected List<JButton> rating_buttons = new ArrayList<JButton>();
    protected Boolean already_rated = false;
    
    protected User user;
    protected List<AnimeList> anime_lists;

    public AnimeDetailPage(MainPage main, Anime source_anime) {
        this.main_page = main;
        this.user = this.main_page.loggedUser;
        this.source_anime = source_anime;
        this.already_rated = false;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.avisoLabel.setVisible(false);
        this.updateElements(this.source_anime);
        this.addRatingButtons();
        this.updateAvailableLists();
        this.updateAddButtonEnabled();
    }
    
    protected void addRatingButtons() {
        this.animeRatingHold.removeAll();
        AnimeRatingDAO dao = new AnimeRatingDAO();
        int rating = dao.get_anime_rating(source_anime, this.main_page.loggedUser);
        already_rated = rating != -1;
        for (int idx = 1; idx <= 5; idx++) {
            JButton button = new JButton();
            button.setMinimumSize(new Dimension(32, 32));
            button.setPreferredSize(new Dimension(32, 32));
            if (rating < idx) {
                button.setIcon(new ImageIcon(getClass().getResource("/assets/empty-star.png")));
            } else {
                button.setIcon(new ImageIcon(getClass().getResource("/assets/full-star.png")));
            }
            
            int this_rating = idx;
            button.addActionListener((ActionEvent e) -> {
                if (!already_rated) {
                    dao.add_rating_to_anime(source_anime, this.main_page.loggedUser, this_rating);
                    already_rated = true;
                } else {
                    dao.update_anime_rating(source_anime, this.main_page.loggedUser, this_rating);
                }
                this.updateRatingButtons();
            });
                
            this.rating_buttons.add(button);
            this.animeRatingHold.add(button);
        }
        
        updateRatingButtons();
    }
    public void updateRatingButtons() {
        AnimeRatingDAO dao = new AnimeRatingDAO();
        int rating = dao.get_anime_rating(source_anime, this.main_page.loggedUser);
        this.avgRating.setText(String.format("%.2f", dao.get_average_anime_rating(source_anime)));
        for (int idx = 1; idx <= 5; idx++) {
            JButton button = this.rating_buttons.get(idx - 1);
            if (rating < idx) {
                button.setIcon(new ImageIcon(getClass().getResource("/assets/empty-star.png")));
            } else {
                button.setIcon(new ImageIcon(getClass().getResource("/assets/full-star.png")));
            }
            button.repaint();
        }
        this.pack();
    }
    
    protected void updateAvailableLists() {
        this.listComboBox.removeAllItems();
        AnimeListDAO dao = new AnimeListDAO();
        List<AnimeList> lists = dao.get_user_lists(this.user);
        for (AnimeList list : lists) {
            this.listComboBox.addItem(list.getName());
        }
        this.anime_lists = lists;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        animeName = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        animeRatingHold = new javax.swing.JPanel();
        animeSRating = new javax.swing.JButton();
        animeSRating1 = new javax.swing.JButton();
        animeSRating2 = new javax.swing.JButton();
        animeSRating3 = new javax.swing.JButton();
        animeSRating4 = new javax.swing.JButton();
        avgRating = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        listComboBox = new javax.swing.JComboBox<>();
        addToListButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        avisoLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        animeDescriptionScroll = new javax.swing.JScrollPane();
        animeDescription = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 134));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 35));

        animeName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        animeName.setText("Nome muito legal do anime legal");
        jPanel1.add(animeName);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshButton);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 60));

        animeRatingHold.setMaximumSize(new java.awt.Dimension(32767, 50));

        animeSRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/empty-star.png"))); // NOI18N
        animeRatingHold.add(animeSRating);

        animeSRating1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/empty-star.png"))); // NOI18N
        animeRatingHold.add(animeSRating1);

        animeSRating2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/empty-star.png"))); // NOI18N
        animeRatingHold.add(animeSRating2);

        animeSRating3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/empty-star.png"))); // NOI18N
        animeRatingHold.add(animeSRating3);

        animeSRating4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/empty-star.png"))); // NOI18N
        animeRatingHold.add(animeSRating4);

        jPanel2.add(animeRatingHold);

        avgRating.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avgRating.setText("5.0");
        jPanel2.add(avgRating);

        listComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista 1", "Lista 2" }));
        listComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listComboBoxItemStateChanged(evt);
            }
        });
        jPanel3.add(listComboBox);

        addToListButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToListButton.setText("+");
        addToListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToListButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addToListButton);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 30));

        avisoLabel.setText("Aviso:");
        jPanel5.add(avisoLabel);

        getContentPane().add(jPanel5);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descrição:");
        jLabel1.setToolTipText("");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4);

        animeDescription.setEditable(false);
        animeDescriptionScroll.setViewportView(animeDescription);

        getContentPane().add(animeDescriptionScroll);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        AnimeDAO dao = new AnimeDAO();
        Anime updated_anime = dao.getAnime(this.source_anime.getId());
        this.source_anime = updated_anime;
        this.updateElements(source_anime);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToListButtonActionPerformed
        AnimeListDAO dao = new AnimeListDAO();
        AnimeList list = this.anime_lists.get(this.listComboBox.getSelectedIndex());
        if (list == null) {
            return;
        }
        
        if (dao.is_anime_in_list(list, source_anime)) {
            this.addToListButton.setEnabled(false);
            return;
        }
        
        dao.add_anime_to_list(list, source_anime, -1);
        this.addToListButton.setEnabled(false);
    }//GEN-LAST:event_addToListButtonActionPerformed

    private void listComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listComboBoxItemStateChanged
        updateAddButtonEnabled();
    }//GEN-LAST:event_listComboBoxItemStateChanged
    
    protected void updateAddButtonEnabled() {
        if (this.anime_lists == null) {
            return;
        }
        AnimeListDAO dao = new AnimeListDAO();
        if (this.anime_lists.isEmpty()) {
            return;
        }
        AnimeList list = this.anime_lists.get(this.listComboBox.getSelectedIndex());
        if (list == null) {
            this.addToListButton.setEnabled(false);
            return;
        }
        
        if (dao.is_anime_in_list(list, source_anime)) {
            this.addToListButton.setEnabled(false);
            return;
        }
        
        this.addToListButton.setEnabled(true);
    }
    
    public void updateElements(Anime anime) {
        this.animeName.setText(anime.getName());
        this.animeDescription.setText(anime.getDescription());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToListButton;
    private javax.swing.JTextPane animeDescription;
    private javax.swing.JScrollPane animeDescriptionScroll;
    private javax.swing.JLabel animeName;
    private javax.swing.JPanel animeRatingHold;
    private javax.swing.JButton animeSRating;
    private javax.swing.JButton animeSRating1;
    private javax.swing.JButton animeSRating2;
    private javax.swing.JButton animeSRating3;
    private javax.swing.JButton animeSRating4;
    private javax.swing.JLabel avgRating;
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> listComboBox;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables


}
