/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;
import model.User;

/**
 *
 * @author andre
 */
public class LoginDialog extends javax.swing.JFrame {
    public User loggedUser;
    protected MainPage mainScreen;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginDialog.class.getName());

    /**
     * Creates new form TelaLogin
     * @param mainScreen
     */
    public LoginDialog(MainPage mainScreen) {
        this.mainScreen = mainScreen;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        avisoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        signupButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(250, 200));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        avisoLabel.setEnabled(false);
        jPanel6.add(avisoLabel);

        getContentPane().add(jPanel6);

        jLabel1.setText("Username");
        jPanel2.add(jLabel1);

        usernameField.setText("your_username");
        jPanel2.add(usernameField);

        getContentPane().add(jPanel2);

        jLabel2.setText("Password");
        jPanel3.add(jLabel2);

        passwordField.setText("your_password");
        jPanel3.add(passwordField);

        getContentPane().add(jPanel3);

        signupButton.setText(" Signup");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        jPanel5.add(signupButton);

        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel5.add(loginButton);

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        UserDAO dao = new UserDAO();
        User target_user = dao.get_user(usernameField.getText());
        if (target_user == null) {
            avisoLabel.setVisible(true);
            avisoLabel.setText("Usuário não encontrado");
            return;
        }
        if (!this.passwordField.getText().equals(target_user.getPassword())) {
            System.out.println("Senha errada");
            avisoLabel.setVisible(true);
            avisoLabel.setText("Senha errada...");
            return;
        }
        
        System.out.println("Usuário logado com sucesso | id: " + target_user.getId());
        this.loggedUser = target_user;
        mainScreen.loggedUser = this.loggedUser;
        this.mainScreen.updateTabs();
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        UserDAO dao = new UserDAO();
        User target_user = dao.get_user(usernameField.getText());
        if (target_user != null) {
            System.out.println("Algum usuário já está usando esse username");
            avisoLabel.setVisible(true);
            avisoLabel.setText("Username já foi utilizado");
            return;
        }
        
        User user = new User(
                -1,
                this.usernameField.getText(),
                this.passwordField.getText()
        );
        dao.create(user);
        this.loggedUser = dao.get_user(usernameField.getText());
        System.out.println("Usuário criado com sucesso | id: " + this.loggedUser.getId());
        mainScreen.loggedUser = this.loggedUser;
        this.mainScreen.updateTabs();
        this.dispose();
    }//GEN-LAST:event_signupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
