/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AnimeDAO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Anime;
import model.User;

/**
 *
 * @author andre
 */
public class MainPage extends javax.swing.JFrame {
    protected User loggedUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPage.class.getName());

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        updateAnimeList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        profileButton = new javax.swing.JButton();
        manageAnimesButton = new javax.swing.JButton();
        animeScroll = new javax.swing.JScrollPane();
        animeList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        navbar.setMaximumSize(new java.awt.Dimension(32767, 30));
        navbar.setPreferredSize(new java.awt.Dimension(400, 50));
        navbar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        navbar.add(profileButton);

        manageAnimesButton.setText("Gerenciar Animes");
        manageAnimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAnimesButtonActionPerformed(evt);
            }
        });
        navbar.add(manageAnimesButton);

        getContentPane().add(navbar);

        animeList.setLayout(new javax.swing.BoxLayout(animeList, javax.swing.BoxLayout.Y_AXIS));
        animeScroll.setViewportView(animeList);

        getContentPane().add(animeScroll);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        LoginPage login_screen = new LoginPage(this);
        login_screen.setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void manageAnimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAnimesButtonActionPerformed
        ManageAnimesPage manage_screen = new ManageAnimesPage(this);
        manage_screen.setVisible(true);
    }//GEN-LAST:event_manageAnimesButtonActionPerformed

    public void lookIntoAnime(Anime anime) {
        System.out.println("Oi eu cliquei no anime: " + anime.getId());
    }
    
    public void updateAnimeList() {
        AnimeDAO anime_dao = new AnimeDAO();
        this.animeList.removeAll();
        List<Anime> animes = anime_dao.list();
        for (Anime anime : animes) {
            JPanel anime_info_holder = new JPanel();
            anime_info_holder.setLayout(new BoxLayout(anime_info_holder, BoxLayout.X_AXIS));
            anime_info_holder.setMaximumSize(new Dimension(1920, 30));
            
            JPanel label_holder = new JPanel();
            label_holder.setLayout(new FlowLayout(FlowLayout.LEFT));
            JLabel name_label = new JLabel(anime.getName());
            label_holder.add(name_label);
            
            JPanel button_holder = new JPanel();
            button_holder.setLayout(new FlowLayout(FlowLayout.RIGHT));
            JButton look_into = new JButton("Ver");
            look_into.addActionListener((ActionEvent e) -> {
                lookIntoAnime(anime);
            });
            
            button_holder.add(look_into);
            
            anime_info_holder.add(label_holder);
            anime_info_holder.add(new JPanel());
            anime_info_holder.add(button_holder);
            this.animeList.add(anime_info_holder);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            System.getLogger(MainPage.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animeList;
    private javax.swing.JScrollPane animeScroll;
    private javax.swing.JButton manageAnimesButton;
    private javax.swing.JPanel navbar;
    private javax.swing.JButton profileButton;
    // End of variables declaration//GEN-END:variables
}
