/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AnimeDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Anime;

/**
 *
 * @author andre
 */
public class ManageAnimesPage extends javax.swing.JFrame {
    protected int selected_id;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAnimesPage.class.getName());

    /**
     * Creates new form ManageAnimes
     */
    public ManageAnimesPage() {
        initComponents();        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        animeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setText("ID");
        jPanel6.add(jLabel3);

        jLabel1.setText("Nome");
        jPanel6.add(jLabel1);

        jPanel7.add(jPanel6);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        idField.setEditable(false);
        idField.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel2.add(idField);

        nameField.setText("nome do anime");
        nameField.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        nameField.setMinimumSize(new java.awt.Dimension(150, 22));
        jPanel2.add(nameField);

        jPanel7.add(jPanel2);

        jPanel1.add(jPanel7);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Descrição");
        jPanel3.add(jLabel2);

        descriptionArea.setColumns(20);
        descriptionArea.setLineWrap(true);
        descriptionArea.setRows(5);
        jScrollPane2.setViewportView(descriptionArea);

        jPanel3.add(jScrollPane2);

        jPanel1.add(jPanel3);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel5.add(refreshButton);

        submitButton.setText("Inserir");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel5.add(submitButton);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        animeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        animeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(animeTable);

        jPanel4.add(jScrollPane1);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        AnimeDAO dao = new AnimeDAO();
        Anime anime = new Anime(
                -1,
                this.nameField.getText(),
                this.descriptionArea.getText()
        );
        dao.create(anime);
        this.updateTable();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        int selected_line = this.animeTable.getSelectedRow();
        
        this.selected_id = (int) this.animeTable.getValueAt(selected_line, 0);
        this.idField.setText("" + this.selected_id);
        this.submitButton.setText("Editar");
        this.nameField.setText(this.animeTable.getValueAt(selected_line, 1).toString());
        this.descriptionArea.setText(this.animeTable.getValueAt(selected_line, 2).toString());
    }//GEN-LAST:event_jScrollPane1MouseClicked
    
    public void updateTable() {
        AnimeDAO dao = new AnimeDAO();
        DefaultTableModel model = (DefaultTableModel) this.animeTable.getModel();
        model.setRowCount(0);
        
        List<Anime> animes = dao.list();
        for (Anime anime : animes) {
            model.addRow(new Object[]{
                anime.getId(),
                anime.getName(),
                anime.getDescription()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageAnimesPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable animeTable;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
