/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AnimeListDAO;
import dao.AnimeRatingDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Anime;
import model.AnimeList;
import model.User;

/**
 *
 * @author andre
 */
public class MyListsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyListsPage.class.getName());
    protected MainPage main_page;
    protected User user;
    protected List<AnimeList> anime_lists;
    
    protected int selected_row = -1;
    
    /**
     * Creates new form MyListsPAge
     * @param main
     * @param user
     */
    public MyListsPage(MainPage main, User user) {
        this.main_page = main;
        this.user = user;
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.updateAvailableLists();
        this.updateAnimesInList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listNameField = new javax.swing.JTextField();
        addList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        selectedListComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        animeTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        moveDown = new javax.swing.JButton();
        moveUp = new javax.swing.JButton();
        removeFromList = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Nome da Lista:");
        jPanel1.add(jLabel1);

        listNameField.setMinimumSize(new java.awt.Dimension(100, 22));
        listNameField.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel1.add(listNameField);

        addList.setText("Adicionar Lista");
        addList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListActionPerformed(evt);
            }
        });
        jPanel1.add(addList);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Lista Selecionada:");
        jPanel2.add(jLabel2);

        selectedListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(selectedListComboBox);

        getContentPane().add(jPanel2);

        animeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Position", "Anime Name", "Average Rating", "Your Rating", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        animeTable.setShowGrid(false);
        animeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(animeTable);
        if (animeTable.getColumnModel().getColumnCount() > 0) {
            animeTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            animeTable.getColumnModel().getColumn(2).setPreferredWidth(16);
            animeTable.getColumnModel().getColumn(3).setPreferredWidth(16);
            animeTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1);

        moveDown.setText("Mover para baixo");
        moveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownActionPerformed(evt);
            }
        });
        jPanel3.add(moveDown);

        moveUp.setText("Mover para cima");
        moveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpActionPerformed(evt);
            }
        });
        jPanel3.add(moveUp);

        removeFromList.setText("Remover");
        removeFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromListActionPerformed(evt);
            }
        });
        jPanel3.add(removeFromList);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel3.add(refreshButton);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListActionPerformed
        AnimeListDAO dao = new AnimeListDAO();
        dao.create(this.user, this.listNameField.getText());
        this.updateAvailableLists();
    }//GEN-LAST:event_addListActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateAvailableLists();
        updateAnimesInList();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void removeFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromListActionPerformed
        if (this.selected_row == -1) {
            return;
        }
        AnimeList selected_list = this.anime_lists.get(this.selectedListComboBox.getSelectedIndex());
        AnimeListDAO dao = new AnimeListDAO();
        int anime_id = (int) this.animeTable.getValueAt(this.selected_row, 4);
        System.out.println("Removendo anime id: " + anime_id);
        dao.remove_from_list(selected_list, new Anime(anime_id, "", ""));
        
        this.updateAvailableLists();
        this.updateAnimesInList();
    }//GEN-LAST:event_removeFromListActionPerformed

    private void animeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animeTableMouseClicked
        int selected_line = this.animeTable.getSelectedRow();
        if (selected_line == -1) {
            return;
        }
        this.selected_row = selected_line;
    }//GEN-LAST:event_animeTableMouseClicked

    private void moveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpActionPerformed
        boolean moved = moveAnimeToPosition(this.selected_row, this.selected_row);
        if (moved) {
            this.selected_row -= 1;
            this.animeTable.setRowSelectionInterval(this.selected_row, this.selected_row);
        }
    }//GEN-LAST:event_moveUpActionPerformed

    private void moveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownActionPerformed
        boolean moved = moveAnimeToPosition(this.selected_row, this.selected_row + 2);
        if (moved) {
            this.selected_row += 1;
            this.animeTable.setRowSelectionInterval(this.selected_row, this.selected_row);
        }
    }//GEN-LAST:event_moveDownActionPerformed

    protected boolean moveAnimeToPosition(int row, int pos) {
        if (pos >= this.animeTable.getRowCount() + 1) {
            return false;
        }
        
        if (pos <= 0) {
            return false;
        }
        
        DefaultTableModel model = (DefaultTableModel) this.animeTable.getModel();
        int current_pos = (int) model.getValueAt(row, 0);
        model.setValueAt(model.getValueAt(pos - 1, 0), row, 0);
        model.setValueAt(current_pos, pos - 1, 0);
        model.moveRow(row, row, pos - 1);
        return true;
    }
    
    protected void updateAvailableLists() {
        this.selectedListComboBox.removeAllItems();
        AnimeListDAO dao = new AnimeListDAO();
        List<AnimeList> lists = dao.get_user_lists(this.user);
        for (AnimeList list : lists) {
            this.selectedListComboBox.addItem(list.getName());
        }
        this.anime_lists = lists;
    }
    
    protected void updateAnimesInList() {
        if (this.selectedListComboBox.getItemCount() <= 0) {
            return;
        }
        AnimeList selected_list = this.anime_lists.get(this.selectedListComboBox.getSelectedIndex());
        DefaultTableModel model = (DefaultTableModel) this.animeTable.getModel();
        model.setRowCount(0);
        if (selected_list == null) {
            return;
        }
        
        AnimeListDAO dao = new AnimeListDAO();
        ArrayList<Anime> animes = dao.get_animes_in_list(selected_list);
        AnimeRatingDAO rating_dao = new AnimeRatingDAO();
        
        int pos = 1;
        for (Anime anime : animes) {
            int position = anime.getPosition();
            if (position == -1 || position >= animes.size() + 1 || position <= pos) {
                position = pos;
            }
            
            model.addRow(new Object[] {
                position,
                anime.getName(),
                rating_dao.get_average_anime_rating(anime),
                anime.getRating(),
                anime.getId()
            });
            dao.update_anime_position(selected_list, anime, pos);
            pos += 1;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addList;
    private javax.swing.JTable animeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField listNameField;
    private javax.swing.JButton moveDown;
    private javax.swing.JButton moveUp;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeFromList;
    private javax.swing.JComboBox<String> selectedListComboBox;
    // End of variables declaration//GEN-END:variables
}
