/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import sistemalocacaobikes.dao.ClienteDAO;

/**
 *
 * @author Etec
 */
public class TelaClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaClientes.class.getName());

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
        
        listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        FormFieldRow4 = new javax.swing.JPanel();
        Label4 = new javax.swing.JLabel();
        currentId = new javax.swing.JTextField();
        FormFieldRow = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        FormFieldRow1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        FormFieldRow2 = new javax.swing.JPanel();
        Label2 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        FormFieldRow3 = new javax.swing.JPanel();
        Label3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        sendForm = new javax.swing.JButton();
        RightPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        scrollTabelaClientes = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        LeftPanel.setLayout(new javax.swing.BoxLayout(LeftPanel, javax.swing.BoxLayout.Y_AXIS));

        Label4.setText("Selected ID");
        FormFieldRow4.add(Label4);

        currentId.setEditable(false);
        currentId.setText("-1");
        currentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentIdActionPerformed(evt);
            }
        });
        FormFieldRow4.add(currentId);

        LeftPanel.add(FormFieldRow4);

        Label.setText("Nome");
        FormFieldRow.add(Label);

        txtNome.setText("Seu nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        FormFieldRow.add(txtNome);

        LeftPanel.add(FormFieldRow);

        Label1.setText("CPF");
        FormFieldRow1.add(Label1);

        txtCPF.setText("000.000.000-54");
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        FormFieldRow1.add(txtCPF);

        LeftPanel.add(FormFieldRow1);

        Label2.setText("Telefone");
        FormFieldRow2.add(Label2);

        txtTelefone.setText("149912345678");
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        FormFieldRow2.add(txtTelefone);

        LeftPanel.add(FormFieldRow2);

        Label3.setText("E-mail");
        FormFieldRow3.add(Label3);

        txtEmail.setText("email@gmail.com");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        FormFieldRow3.add(txtEmail);

        LeftPanel.add(FormFieldRow3);

        sendForm.setText("Enviar");
        sendForm.setAlignmentY(0.0F);
        sendForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFormActionPerformed(evt);
            }
        });
        LeftPanel.add(sendForm);

        getContentPane().add(LeftPanel);

        RightPanel.setLayout(new javax.swing.BoxLayout(RightPanel, javax.swing.BoxLayout.Y_AXIS));

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton);

        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);

        RightPanel.add(jPanel1);

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nome", "cpf", "telefone", "email"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        scrollTabelaClientes.setViewportView(tabelaClientes);

        RightPanel.add(scrollTabelaClientes);

        getContentPane().add(RightPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void sendFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFormActionPerformed
        Cliente c = new Cliente();
        c.setNome(txtNome.getText());
        c.setCpf(txtCPF.getText());
        c.setTelefone(txtTelefone.getText());
        c.setEmail(txtEmail.getText());
        
        ClienteDAO dao = new ClienteDAO();

        dao.create(c);
        listarClientes();
    }//GEN-LAST:event_sendFormActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        Cliente c = new Cliente();
        c.setId(this.selectedId);
        c.setNome(txtNome.getText());
        c.setCpf(txtCPF.getText());
        c.setTelefone(txtTelefone.getText());
        c.setEmail(txtEmail.getText());
        
        ClienteDAO dao = new ClienteDAO();
        dao.update(c);
        listarClientes();
        
        this.selectedId = -1;
        currentId.setText("");
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (this.selectedId == -1) {
            System.out.println("Nenhum cliente foi selecionado para deletar");
            return;
        }
        
        Cliente cliente = new Cliente();
        cliente.setId(this.selectedId);
        
        ClienteDAO dao = new ClienteDAO();
        dao.delete(cliente);
        listarClientes();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        int linhaSelecionada = tabelaClientes.getSelectedRow();
        System.out.println(linhaSelecionada);

        this.selectedId = Integer.parseInt(tabelaClientes.getValueAt(linhaSelecionada, 0).toString());
        currentId.setText("" + this.selectedId);
        txtNome.setText(tabelaClientes.getValueAt(linhaSelecionada, 1).toString());
        txtCPF.setText(tabelaClientes.getValueAt(linhaSelecionada, 2).toString());
        txtTelefone.setText(tabelaClientes.getValueAt(linhaSelecionada, 3).toString());
        txtEmail.setText(tabelaClientes.getValueAt(linhaSelecionada, 4).toString());
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void currentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentIdActionPerformed
    
    public void listarClientes() {
        List<Cliente> lista = new ClienteDAO().read();
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setRowCount(0); // Limpa a tabela
        
        for (Cliente c : lista) {
            modelo.addRow(new Object[]{c.getId(), c.getNome(), c.getCpf(),
            c.getTelefone(), c.getEmail()});
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaClientes().setVisible(true));
    }

    private int selectedId = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormFieldRow;
    private javax.swing.JPanel FormFieldRow1;
    private javax.swing.JPanel FormFieldRow2;
    private javax.swing.JPanel FormFieldRow3;
    private javax.swing.JPanel FormFieldRow4;
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JTextField currentId;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollTabelaClientes;
    private javax.swing.JButton sendForm;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
